### ISSUE TITLE
macOS ts-node error

### ISSUE THREAD

**Issue by FrankC01** [solana-labs/example-helloworld#142]
Attempting to `npm run start` failed with sh: ts-node: command not found

I had to do:
```
npm install -D typescript
npm install -D ts-node
```

Worked after that

**Comment by pjuangph** [comment]
I see ts-node permission denied when I try running it. sudo doesn't help either.

**Comment by jstarry** [comment]
Looks like this would be resolved with `npm install`, maybe it wasn't run after updating to latest master? @pjuangph feel free to open a separate issue if you're experiencing that problem
