### ISSUE TITLE
'solana-test-validator' not found

### ISSUE THREAD

**Issue by axeldelamarre** [solana-labs/example-helloworld#164]
I installed solana as per the instructions but the command is not found. Did I miss something?

**Comment by axeldelamarre** [comment]
Fixed by switching to WSL

**Comment by gaa2118** [comment]
Hey axeldelamarre, I think I'm stuck at the same part you were, how did you fix the issue? I downloaded the WSL, how did you get the prebuilt binaries? I appreciate the help

**Comment by axeldelamarre** [comment]
Hmm I think that command came with the whole Solana package

**Comment by gaa2118** [comment]
How did you run the WSL?

**Comment by axeldelamarre** [comment]
I run WSL 2 with Ubuntu

**Comment by NicolaBernini** [comment]
Hi folks, 

to solve this problem you might be interested in my Dockerized version of Solana 

https://github.com/NicolaBernini/Solana-Dockerized
