### ISSUE TITLE
FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899

### ISSUE THREAD

**Issue by AuroraLantean** [solana-labs/example-helloworld#169]
Hi I am trying to run this hello world in my Linux Mint distro with all the latest dev environment:
NodeJs: 15.14.0, 
solana-cli 1.6.4 
rustc 1.51.0
docker 19.03.12, build 48a66213fe

I downloaded this repo, changed the node version in package.json
  "engines": {
    "node": "15.x"
  }
And also re-installed @solana/web3.js to the latest: ^1.2.6

Then I followed the ReadMe:
Enable on-chain program log: $ export RUST_LOG=...

Start a local Solana cluster: $ solana-test-validator --log

$ yarn install
$ yarn run build:program-rust
$ yarn run start
Then I got this:

yarn run v1.22.4
$ ts-node src/client/main.ts
Let's say hello to a Solana account...
FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899
    at ClientRequest.<anonymous> (/mnt/sda5/0Programming/Solana/example-helloworld/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:369:20)
    at ClientRequest.emit (node:domain:470:12)
    at Socket.socketErrorListener (node:_http_client:472:9)
    at Socket.emit (node:events:369:20)
    at Socket.emit (node:domain:470:12)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
It seems the Solana node is not running... 
I have also tried those but still not working:
$ yarn run cluster:localnet

$ solana config get
Config File: /home/user1/.config/solana/cli/config.yml
RPC URL: https://api.mainnet-beta.solana.com 
WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
Keypair Path: /home/user1/.config/solana/id.json 
Commitment: confirmed 

$ solana --version                                 
solana-cli 1.6.4 (src:b04ce802; feat:3342604240)

$ solana cluster-version
1.5.19

Did you miss that in the Readme? how to fix this? Please help. Thank you

**Comment by AmagiDDmxh** [comment]
This might happens becuase none of cluster is running locally, run `yarn cluster:devnet` or `yanr cluster:[the-network]` to run on remote server should be cool?

**Comment by jstarry** [comment]
@AuroraLantean `solana-test-validator` needs to keep running while you run `yarn run start`
