### ISSUE TITLE
no such subcommand: `build-bpf`

### ISSUE THREAD

**Issue by ateeqrehmani** [solana-labs/example-helloworld#190]
npm run build:program-rust giving me this error no such subcommand: `build-bpf`
below is the .log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:program-rust'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [
4 verbose run-script   'prebuild:program-rust',
4 verbose run-script   'build:program-rust',
4 verbose run-script   'postbuild:program-rust'
4 verbose run-script ]
5 info lifecycle helloworld@0.0.1~prebuild:program-rust: helloworld@0.0.1
6 info lifecycle helloworld@0.0.1~build:program-rust: helloworld@0.0.1
7 verbose lifecycle helloworld@0.0.1~build:program-rust: unsafe-perm in lifecycle true
8 verbose lifecycle helloworld@0.0.1~build:program-rust: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ateeq/projects/code/rust - hellowordl/example-helloworld/node_modules/.bin:/home/ateeq/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
9 verbose lifecycle helloworld@0.0.1~build:program-rust: CWD: /home/ateeq/projects/code/rust - hellowordl/example-helloworld
10 silly lifecycle helloworld@0.0.1~build:program-rust: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program'
10 silly lifecycle ]
11 silly lifecycle helloworld@0.0.1~build:program-rust: Returned: code: 101  signal: null
12 info lifecycle helloworld@0.0.1~build:program-rust: Failed to exec build:program-rust script
13 verbose stack Error: helloworld@0.0.1 build:program-rust: `cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program`
13 verbose stack Exit status 101
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid helloworld@0.0.1
15 verbose cwd /home/ateeq/projects/code/rust - hellowordl/example-helloworld
16 verbose Linux 5.4.0-65-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:program-rust"
18 verbose node v14.15.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 101
22 error helloworld@0.0.1 build:program-rust: `cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program`
22 error Exit status 101
23 error Failed at the helloworld@0.0.1 build:program-rust script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 101, true ]

**Comment by jstarry** [comment]
@ateeqrehmani have you installed the Solana CLI tools? https://docs.solana.com/cli/install-solana-cli-tools

**Comment by ateeqrehmani** [comment]
@jstarry yes i did.
solana --version was giving me 
solana-cli 1.6.6 (src:fe775a97; feat:3714435735)

After restarting my system issue is fixed now.

**Comment by Sirius-LeeFeng** [comment]
@jstarry @ateeqrehmani hi~ l also got this. But  restarted system measure can't resolve  the problem.

macOS:10.13.6
node14

liqideMBP:~ sirius$ solana --version
solana-cli 1.6.8 (src:28b9e5b5; feat:3458834192)

liqideMBP:example-helloworld sirius$ npm run build:program-rust

> helloworld@0.0.1 build:program-rust /Users/sirius/IdeaProjects/example-helloworld
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /Users/sirius/.local/share/solana/install/releases/1.6.8/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sirius/.rustup/toolchains/bpf/bin/cargo (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sirius/.rustup/toolchains/bpf/bin/cargo (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@0.0.1 build:program-rust: `cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 build:program-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sirius/.npm/_logs/2021-05-15T13_20_46_741Z-debug.log

**Comment by ateeqrehmani** [comment]
@Sirius-LeeFeng It seems like issue is related to Mac OS, I was facing the issue on ubuntu.

**Comment by jstarry** [comment]
@Sirius-LeeFeng I recommend using an updated version of macos or installing the tools from source
