### ISSUE TITLE
solana/localhost error

### ISSUE THREAD

**Issue by vvmmaann** [solana-labs/example-helloworld#206]
i've just tried to run the testnet node and everything went fine except the part with 

solana catchup ~/solana/validator-keypair.json

it can't see my pubkey 
and when i try this 
 solana catchup validator-keypair.json --our-localhost

it says:
Error: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 111)

Please help with fixing that. Thanks

**Comment by jstarry** [comment]
@vvmmaann sorry for the delay. This problem is not related to the hello world example, I recommend you ask in Discord: http://solana.com/discord
