### ISSUE TITLE
unable to get packages from source

### ISSUE THREAD

**Issue by Grodriggues** [solana-labs/example-helloworld#258]
Error when running  _**npm run build:program-rust**_

cargo 1.53.0 (4369396ce 2021-04-27)

`error: failed to download `zeroize v1.4.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  feature `resolver` is required`

**Comment by jeffhu1** [comment]
Seconded

**Comment by raymondjacobson** [comment]
This isn't a fantastic solution, but if you do hit this error, you can get around it by removing the Cargo.lock that's checked in (https://github.com/solana-labs/example-helloworld/blob/master/src/program-rust/Cargo.lock) and running `npm run build:program-rust` again

**Comment by raymondjacobson** [comment]
This isn't a fantastic solution, but if you do hit this error, you can get around it by checking out the updated Cargo.lock in src/program-rust and running npm run build:program-rust again.

```
npm i
git checkout src/program-rust
npm run build:program-rust again
```

**Comment by chowdhury-bc** [comment]
Getting similiar issue. i have tried using the zeroize's cargo.toml.orig file to get around the zeroize issue ( the current one has resolver="2"). 
But now i am getting socket2 issue. 
https://github.com/rust-lang/socket2/issues/250

**Comment by chowdhury-bc** [comment]
> This isn't a fantastic solution, but if you do hit this error, you can get around it by checking out the updated Cargo.lock in src/program-rust and running npm run build:program-rust again.
> 
> ```
> npm i
> git checkout src/program-rust
> npm run build:program-rust
> ```
> 
> Or you could manually set the zeroize version back to `zeroize = "=1.3.0"` in the Cargo.toml file in the rust program and run `npm i` again



> This isn't a fantastic solution, but if you do hit this error, you can get around it by checking out the updated Cargo.lock in src/program-rust and running npm run build:program-rust again.
> 
> ```
> npm i
> git checkout src/program-rust
> npm run build:program-rust
> ```
> 
> Or you could manually set the zeroize version back to `zeroize = "=1.3.0"` in the Cargo.toml file in the rust program and run `npm i` again

This workaround worked for me. thank you for your help

**Comment by CriesofCarrots** [comment]
Updating your solana install to v1.7.8 should also resolve the issue (Cargo.lock/Cargo.toml manipulations no longer needed)
I'll update the docs to recommend that version.
