### ISSUE TITLE
Running: cargo +bpf build --target bpfel-unknown-unknown --release error: failed to download `zeroize v1.4.1`

### ISSUE THREAD

**Issue by chowdhury-bc** [solana-labs/example-helloworld#259]
I have installed latest version of `rustc` and `cargo` but still getting the issue.

**Comment by CriesofCarrots** [comment]
Zeroize v1.4 introduced a breaking change via some of our bpf dependencies. You'll either need to manually edit your Cargo.lock back to v1.3, or upgrade your solana tools to v1.7.7 to pull in the fix (technically still a pre-release, but will be announced for testnet shortly)

I'm not sure if you encountered this in an existing program/repo, or what, but in future, you may be able to avoid such breakages by keeping your Cargo.lock file committed.
