### ISSUE TITLE
no such subcommand: `+bpf`

### ISSUE THREAD

**Issue by filmediaonline** [solana-labs/example-helloworld#262]
im new to solana and rust,whenever i try to build the rust program using npm scripts or going to the rust program directory to manually run 'cargo build-bpf', it says - no such subcommand: `+bpf`.

![Screenshot at 2021-07-31 17-13-53](https://user-images.githubusercontent.com/87638730/127730750-a680e81b-280e-4898-b266-be470d09eb57.png)

**Comment by astro-martian** [comment]
either you haven't installed Solana or the PATH is not properly set. 

Follow this guide - https://docs.solana.com/cli/install-solana-cli-tools#use-solanas-install-tool to install Solana and update the PATH accordingly. 

You should get something like `solana-cli 1.7.9 (src:0707290b; feat:2045430982)` with the command `solana --version` after completing the setup
