### ISSUE TITLE
solana-test-validator error on Ubuntu

### ISSUE THREAD

**Issue by thielm** [solana-labs/example-helloworld#264]
Not sure how to get past this error, anyone?

$ solana-test-validator  
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', validator/src/bin/solana-test-validator.rs:294:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Yes I am a noob :-)

**Comment by ayush20** [comment]
facing same issue after following https://github.com/solana-labs/example-helloworld/blob/master/README.md

**Comment by uncle-T0ny** [comment]
To solve the problem, installed the oldest Solana version 
`sh -c "$(curl -sSfL https://release.solana.com/v1.6.6/install)"`

**Comment by jstarry** [comment]
This is an issue on v1.7.9, you can wait for v1.7.10 or downgrade to v1.7.8 or lower. I have updated the docs to recommend installing v1.7.8
