### ISSUE TITLE
TextEncoder is not defined. 

### ISSUE THREAD

**Issue by Saviour1001** [solana-labs/example-helloworld#282]
- [x]  Able to run the cluster on Solana version 1.6.20
- [x] Able to build the rust program on Solana version 1.7.10
- [x] Able to deploy the program on the cluster
- [ ] Facing errors in running the JavaScript Client

Here are the logs
![WhatsApp Image 2021-08-14 at 1 02 48 PM](https://user-images.githubusercontent.com/71517788/129440817-8b5444e9-df62-4eac-ad51-ba96c47f5401.jpeg)

Could someone help with what I am doing wrong or is this a bug? I am guessing that there is a lack of dependencies on my end, but I couldn't solve this error.

**Comment by Jibz795** [comment]
I am facing the exact same issue as you :)

**Comment by Saviour1001** [comment]
Yes, just update the Nodejs and NPM.
