### ISSUE TITLE
Error while running :npm run build:program-rust

### ISSUE THREAD

**Issue by Neha-Jain01** [solana-labs/example-helloworld#290]
getting this error :
> helloworld@0.0.1 build:program-rust /home/neha/example-helloworld
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /home/neha/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: rustup toolchain link bpf /home/neha/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
error: not a directory: '/home/neha/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/bin'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@0.0.1 build:program-rust: `cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld@0.0.1 build:program-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neha/.npm/_logs/2021-08-21T17_12_40_680Z-debug.log

**Comment by jstarry** [comment]
@Neha-Jain01 sorry you ran into this issue, can you try removing `/home/neha/.local/share/solana/install/releases` and reinstalling the solana tools?

```
sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"
```

**Comment by pierreneter** [comment]
I had the same problem and reinstalled Solana CLI version >= `1.7.11` and it works fine.

**Comment by logesh2496** [comment]
I'm still facing the same issue. I removed(.../.local/share/solana/install/releases) and reinstalled the 1.7.11/1.7.12 several times, but still with the below error:

npm run build:program-rust

> helloworld@0.0.1 build:program-rust /home/logesh/solana/example-helloworld
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /home/logesh/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: rustup toolchain link bpf /home/logesh/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
error: not a directory: '/home/logesh/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld@0.0.1 build:program-rust: `cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the helloworld@0.0.1 build:program-rust script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/logesh/.npm/_logs/2021-09-27T06_27_50_490Z-debug.log

@jstarry @pierreneter Please help. Thanks

**Comment by logesh2496** [comment]
Manually deleting the .config/solana/install and reinstalling fixed this issue for me. Thanks!
