### ISSUE TITLE
solana-test-validator Unable to connect to validator: Client error: test-ledger/admin.rpc does not exist

### ISSUE THREAD

**Issue by Coloradete** [solana-labs/example-helloworld#294]
Hi, I'm running an Ubuntu 18.04 WSL2 machine under Windows 10.

When running the `solana-test-validator` line I got the following messages

```
Ledger location: test-ledger
Log: test-ledger/validator.log
Unable to connect to validator: Client error: test-ledger/admin.rpc does not exist
```

I tried with the 1.7.0 version and the LTS solana-cli 1.6.22 (src:45e3cd37; feat:3316993441)

Any clues? thanks!

**Comment by zikyfranky** [comment]
I'm having this very same issue, below is a supporting file.

![Error:admin.rpc](https://user-images.githubusercontent.com/36174178/131297631-1b9c5eca-cafe-4d65-8bc8-0736d6e29e2c.png)

The `test-ledger` folder is created at runtime by the `solana-test-validator` command, so even thinking of getting the file (that's if I find a sample anywhere) externally wouldn't work..

I'm stuck.

**Comment by Coloradete** [comment]
Hello there, I solved it by changing the directories to the WSL home folder (by default it opens on the mounted windows system) and then reinstalling everything again. 
Hope that helps!

**Comment by zikyfranky** [comment]
Sorry, I didn't get that, what directory path did you change?

By reinstalling everything, do you mean EVERYTHING? (Solana-cli, wsl .. etc)?

Thanks

**Comment by Coloradete** [comment]
I did reinstall everything to make sure nothing get messed up (even the virtual machine) but maybe you can try without doing that first. 

![imagen](https://user-images.githubusercontent.com/48124115/131311194-fd1990cb-e2ee-4342-b995-7e279aeb8b1b.png)

See the /mnt/c/Users/... ? that means that you are on a mounted windows image inside your WSL Ubuntu (or whatever distro you installed) machine. you should do command cd .. until you are out of the mnt directory and then change to home/<USER_NAME_YOU_CHOOSE>. that will take you out of the windows mounted system to the actual linux WSL, and then working from there everything should be fine. Take into account that everytime you open a new bash it will open by default on the mnt system, so you need to change it.

**Comment by zikyfranky** [comment]
Oh. thanks a bunch, that worked.

I would have been stuck here for like forever 😂
Thanks, I'll just find a way to make ~/<username> the default startup directory.

**Comment by Coloradete** [comment]
glad to help!

**Comment by Meacho** [comment]
> I'm having this very same issue, below is a supporting file.
> 
> ![Error:admin.rpc](https://user-images.githubusercontent.com/36174178/131297631-1b9c5eca-cafe-4d65-8bc8-0736d6e29e2c.png)
> 
> The `test-ledger` folder is created at runtime by the `solana-test-validator` command, so even thinking of getting the file (that's if I find a sample anywhere) externally wouldn't work..
> 
> I'm stuck.

I ran into this issue as well initially. I found out that `solana-test-validator` has to be run from the route directory.
so enter `cd ~/`
then enter `solana-test-validator`

**Comment by aviral17** [comment]
> 

Hi Bro, It didn't worked for me..... Can U please help me ??

**Comment by jasonjgarcia24** [comment]
`cd ~`

**Comment by Tanv33** [comment]
The issue at hand is likely due to your current location within the project. To resolve this, please navigate to the root directory by entering the command `cd ~`. This should alleviate the error and allow for smoother operation. 
Thank you for your attention to this matter.

![image](https://github.com/solana-labs/example-helloworld/assets/79161723/4cef3274-90dd-4c51-95c6-56a3d1b4fe64)

**Comment by Sandatang** [comment]
> The issue at hand is likely due to your current location within the project. To resolve this, please navigate to the root directory by entering the command `cd ~`. This should alleviate the error and allow for smoother operation. Thank you for your attention to this matter.
> 
> ![image](https://user-images.githubusercontent.com/79161723/272198849-4cef3274-90dd-4c51-95c6-56a3d1b4fe64.png)

I am new to web3 development this works for me. but can i still create project to other directory right?

**Comment by minhbear** [comment]
I had face this issue and here is the solution. 
```
Waiting for fees to stabilize 1...
⠋ Unable to connect to validator: Client error: test-ledger/admin.rpc does not exist  
```
This thing can not run because the current directory you open to run the command solana-test-validator is not have the folder test-ledger. 
With that I change to the WSL, in the Home folder (you can use cd ~ to redirect to home folder) install the solana-cli. In here solana-cli also install and store the folder test-ledger

**Comment by MeerUzairWasHere** [comment]
cd /

**Comment by turcottep** [comment]
What worked for me is cd to / 
```
cd /
```

and then adding the --ledger DIR argument:
```
solana-validator --ledger mnt/ledger monitor
```
