### ISSUE TITLE
Validator process aborted. The validator log may contain further details

### ISSUE THREAD

**Issue by 7--** [solana-labs/example-helloworld#296]
```
solana-test-validator
Validator process aborted. The validator log may contain further details
```
I did everything under System Tuning (automatic and manual) but i still get this error.

```
~$ cat test-ledger/validator.log
[2021-08-29T02:05:18.830290897Z WARN  solana_core::validator] CUDA is disabled
[2021-08-29T02:05:18.830321426Z INFO  solana_core::validator] AVX detected
[2021-08-29T02:05:18.830327087Z ERROR solana_core::validator] Incompatible CPU detected: missing AVX2 support. Please build from source on the target
```
https://github.com/solana-labs/example-helloworld#start-local-solana-cluster
Ubuntu 20.04.3 LTS
AMD® Fx(tm)-8120 eight-core processor × 8 

Edit: I tried on my laptop and everything works. I guess my desktop CPU doesn't have AVX2 support and someone would have to rebuild solona on my CPU to get it to work. 

Edit: Will try to build from source using https://github.com/solana-labs/solana#building

**Comment by jstarry** [comment]
@t-nelson do you know what the appropriate fix is here?

**Comment by t-nelson** [comment]
> @t-nelson do you know what the appropriate fix is here?

Gotta build from source

**Comment by 7--** [comment]
After following this tutorial https://github.com/solana-labs/solana#building 

I'm able to run it now using the source code. `./solana/validator/solana-test-validator`
