### ISSUE TITLE
no such subcommand: `+bpf`

### ISSUE THREAD

**Issue by BestSilverTiger** [solana-labs/example-helloworld#349]
When I run the command "npm run build:program-rust"
I faced this issue.

> helloworld@0.0.1 build:program-rust
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /usr/bin/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
error: no such subcommand: `+bpf`

	Did you mean `b`?

What is the solution?

**Comment by walski** [comment]
I (and according to Discord several others) ran into the same issue and just using `rustup` to update the toolchain did not work.

I could resolve it after uninstalling rust through Homebrew and re-installing it through `rustup` ([docs](https://www.rust-lang.org/tools/install)).

**Comment by MarcoBerlot** [comment]
My problem was caused by the installation of both rust and Solana with brew.

 I uninstalled them both, reinstalled them using the curl method suggested in the respective documentations and it worked
