### ISSUE TITLE
 incorrect program id for instruction

### ISSUE THREAD

**Issue by fospring** [solana-labs/example-helloworld#365]
I follow those step but `npm run start` got:failed with log: `incorrect program id for instruction`.Why?

![incorrect-program-id](https://user-images.githubusercontent.com/19633691/141488971-a2128b0d-b94f-4365-92e1-2ecb95791cd7.jpg)

**Comment by fospring** [comment]
It happens when I round local node with `solana-test-validator --no-bpf-jit` on Mac m1

**Comment by vpontis** [comment]
@fospring hi! How'd you fix this? I'm running into the same issue :)

**Comment by saurabhsharan** [comment]
+1, also happening for me when I run the local node with `--no-bpf-jit` (which is needed to run on M1 Mac)

**Comment by Thearas** [comment]
Hi! It works fine when using the `solana-test-validator` compiled  from source (<https://github.com/solana-labs/solana/tree/master/validator>).
@fospring @saurabhsharan @vpontis cc

**Comment by fospring** [comment]
> @fospring hi! How'd you fix this? I'm running into the same issue :)

I solve it by compile `solana-test-validator` `solana` cli  from source(master branch) and `rm ~/.cache/solana` and recompile this program.
@vpontis @Thearas
