### ISSUE TITLE
Rust build fails on Ubuntu 22.04 (cannot find libssl.so)

### ISSUE THREAD

**Issue by grapereader** [solana-labs/example-helloworld#470]
Following the README as written. Fails at the build:program-rust step. Seems to be looking for libssl but cannot find it...

```
dev@dev-vm-crypto:~/repos/example-helloworld$ npm run build:program-rust

> helloworld@0.0.1 build:program-rust
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /home/dev/.local/share/solana/install/releases/stable-157aa16c6b8b3f3d965680c87a8703047e475881/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: rustup toolchain link bpf /home/dev/.local/share/solana/install/releases/stable-157aa16c6b8b3f3d965680c87a8703047e475881/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
/home/dev/.rustup/toolchains/bpf/bin/cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I have libssl-dev installed, as well as other dependencies from root solana project: libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make

**Comment by giorgiocc** [comment]
same problem here.

**Comment by grapereader** [comment]
Nope. I had to switch to Ubuntu 20.04

**Comment by Nwqda** [comment]
Here is the solution to fix this: 
https://github.com/project-serum/anchor/issues/1831

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
```

**Comment by bmeeder22** [comment]
Getting this error as well and above fix returns a 404 while trying to fetch the file ^

**Comment by ZhoufangErqiangu** [comment]
wget nz2.archive got 404.

i found another souce.

http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1_amd64.deb

quote:https://ubuntu.pkgs.org/21.10/ubuntu-main-amd64/libssl1.1_1.1.1l-1ubuntu1_amd64.deb.html

**Comment by ttwo22** [comment]
一样的的问题，我也不行

**Comment by ttwo22** [comment]
> Here is the solution to fix this: [coral-xyz/anchor#1831](https://github.com/coral-xyz/anchor/issues/1831)
> 
> ```
> wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
> sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
> ```

404 Not Found

**Comment by Hashmozy** [comment]
Hi any one who found the solution to the above error on ubuntu 22.04 please?

**Comment by llgiant** [comment]
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb

solved the issue

**Comment by Nok1luck1** [comment]
> 

No such file or directory anyway

**Comment by diwasdhungana** [comment]
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

this works.

**Comment by llgiant** [comment]
> http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openss

архив ставится?

**Comment by Nok1luck1** [comment]
easier way its reinstall Ubuntu to version 20.04.On that version all work fine, even with installing Anchor i have no problem

**Comment by rcolomina** [comment]
This solved the problem for me on my Ubuntu 22.04 machine. Thanks.

`wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb`
`sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb`

**Comment by Hashmozy** [comment]
Thank you but I managed to solve this by installing LSB in my Ubuntu 22.04
by sudo apt install lsb

**Comment by Kartos102** [comment]
> wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
> 
> this works.

It works on my side too
Thanks

**Comment by joncinque** [comment]
Closing since there's a resolution to the problem. In the future, we don't use GitHub for developer support, and encourage you ask your question on the Solana Stack Exchange https://solana.stackexchange.com/ or some other developer support forum.

**Comment by berry-sol** [comment]
The version provided in the solution doesn't exist anymore and you will now receive an **error 404 page does not exists** message.

try this version:
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb

**Comment by itayLev1** [comment]
found this one https://packages.ubuntu.com/focal/amd64/libssl1.1/download

it recommends using:
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb

**Comment by Kartos102** [comment]
I tried this
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb

It works for me

**Comment by andresmgsl** [comment]
This help! Thanks..

**Comment by Karlitoyo** [comment]
This repo has now been updated to 

wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
