### ISSUE TITLE
This version v1.7.11 is not working

### ISSUE THREAD

**Issue by kudarukuni** [solana-labs/example-helloworld#501]
sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"
downloading v1.7.11 installer
Error: Unknown release: 1.7.11

**Comment by katopz** [comment]
I think `v1.7.11` was too old, try present version or select one here https://github.com/solana-labs/solana/releases
```
sh -c "$(curl -sSfL https://release.solana.com/v1.10.26/install)"
```

**Comment by kudarukuni** [comment]
solana-test-validator --log
Aborted
