### ISSUE TITLE
error: no such subcommand: +bpf

### ISSUE THREAD

**Issue by haoyuxin** [solana-labs/example-helloworld#577]
rustc --version 1.66.0
rustup --version 1.25.1
solana --version solana-cli 1.14.11 
window os;
what to do now,please;
however, its ok in wsl2

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for developer support, and encourage you ask your question on the Solana Stack Exchange https://solana.stackexchange.com/ or some other developer support forum.
