### ISSUE TITLE
Connection Reset by Peer

### ISSUE THREAD

**Issue by chronaeon** [solana-labs/example-helloworld#63]
Thanks for the very straightforward README file!

This fail happens at `sudo npm run localnet:up`. Here is what emits from stdout:

```
> helloworld@0.0.1 localnet:up /home/micah/example-helloworld
> set -x; solana-localnet down; set -e; solana-localnet up

+ solana-localnet down
Docker version 19.03.6, build 369ce74a3c
++ docker ps --filter 'name=^solana-localnet$' -q
+ [[ -n 0c5b224cf5c4 ]]
+ docker stop --time 0 solana-localnet
solana-localnet
+ set -e
+ solana-localnet up
Docker version 19.03.6, build 369ce74a3c
+ RUST_LOG=solana=info
+ ARGS=(--detach --name solana-localnet --rm --publish 8899:8899 --publish 8900:8900 --publish 9900:9900 --tty --env "RUST_LOG=$RUST_LOG")
+ [[ -n '' ]]
+ docker run --detach --name solana-localnet --rm --publish 8899:8899 --publish 8900:8900 --publish 9900:9900 --tty --env RUST_LOG=solana=info solanalabs/solana:v1.2.1
e1bb7e7180b1a57a914970030451f16b1e38189292a859ebef6df2f5d034fa65
+ for _ in 1 2 3 4 5
+ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"getTransactionCount"}' http://localhost:8899
curl: (56) Recv failure: Connection reset by peer
+ sleep 1
+ for _ in 1 2 3 4 5
+ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"getTransactionCount"}' http://localhost:8899
curl: (56) Recv failure: Connection reset by peer
+ sleep 1
+ for _ in 1 2 3 4 5
+ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"getTransactionCount"}' http://localhost:8899
{"jsonrpc":"2.0","result":0,"id":1}
+ break
```
I ran all of the prior instructions in the README file without problems, besides having to use sudo a couple times.

**Comment by mvines** [comment]
Hi @chronaeon, this output looks totally fine.  The final curl response was `{"jsonrpc":"2.0","result":0,"id":1}`, indicating one transaction has executed.  The `Connection reset by peer` prior to that are normal while the validator starts up.

I'm going to close this issue as I don't see any action here.  Please comment back if you have any questions or come chat with us interactively in Discord.

**Comment by chronaeon** [comment]
@mvines I guess I'm not understanding -- where is the "Hello World!" aspect manifest in this?

**Comment by chronaeon** [comment]
@mvines glad to learn that the TX executed, and how I would be able to tell in the future. Does the chain on which the one transaction has occurred persist? Or is it wiped from memory right away? If the chain is still around, how can I explore the transaction I've made on it? I

**Comment by mvines** [comment]
You can use the command line tool, https://docs.solana.com/cli, to fetch information about executed transactions.  There's also a JSON RPC API available at https://docs.solana.com/apps/jsonrpc-api

**Comment by chronaeon** [comment]
@mvines Thanks a bunch!
