### ISSUE TITLE
What is solana-localnet script?

### ISSUE THREAD

**Issue by 524119574** [solana-labs/example-helloworld#73]
So I am trying to start a localnet for Solana cluster. And I ran the following (as suggested from the `README`):
```
 npm run localnet:update
```
Then it's telling me:
```
solana-localnet: not found
```
So I am wondering what is this and how can I download/install it? Thanks!

**Comment by joncinque** [comment]
Hi there, you'll need to run `npm install` from the top-level project directory to pull down the solana-localnet script, along with the rest of the dependencies.

**Comment by joncinque** [comment]
https://github.com/solana-labs/example-helloworld/blob/master/README-installation-notes.md contains more setup info for you.  The script provides easy commands to set up / run / update / stop the solana docker container
